apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    access: proxy
    url: cratedb:5432
    database: doc
    user: crate
    secureJsonData:
      password: ""
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1200  # CrateDB é compatível com PostgreSQL 12+
      timescaledb: false
    isDefault: true
    editable: true
